FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    ca-certificates

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

WORKDIR /app

COPY . .

RUN cargo build --release

RUN cp target/release/kaniko-cli /kaniko-cli-linux-amd64

FROM scratch
COPY --from=0 /kaniko-cli-linux-amd64 /kaniko-cli
ENTRYPOINT ["/kaniko-cli"]