name: Release Binaries

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches: 
      - main

permissions:
  contents: write  # Required for creating releases


env:
  VERSION_NAME: ${{ case(github.ref_name == 'main', 'latest', github.ref_name) }}

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
    steps:
      - uses: actions/checkout@v5 # v3

      - name: Setup Rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Build binaries
        # if: ${{ github.ref_name == 'main' }}
        run: |
          cargo build --release

          # compress upx 
          # upx -fq --ultra-brute target/release/kaniko 

          # Create archives
          tar cvf kaniko-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION_NAME }}.tar.gz target/release/kaniko 
          
          # Calculate checksums
          sha256sum kaniko-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION_NAME }}.tar.gz > kaniko-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION_NAME }}.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kaniko-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION_NAME }}.tar.gz
            kaniko-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION_NAME }}.tar.gz.sha256
          generate_release_notes: true
          tag_name: ${{ env.VERSION_NAME }}